import os
os.chdir("I:\ISD2014")
from counter import *
tally = Counter()
cnt = Counter()
tally.setLimit(5)
cnt.setLimit(100)
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
cnt.click()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.reset()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())
tally.undo()
cnt.undo()
print("tally = ", tally.getValue(), "counter = ", cnt.getValue())

